# SPDX-License-Identifier: MIT
---
# Put handlers for tasks here.

# Example:
- name: ssh handler to restart services
  service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ __ssh_services }}"
